name: 'NotionHook'
description: 'Sync your commits to Notion'
branding:
  icon: 'check-circle'  
  color: 'white'
inputs:
  notion_secret:
    description: 'Notion Secret retrieved from My Integrations on notion.so/my-integrations'
    required: true
  commit_url:
    description: "Name of Database column for commit url"
    required: true
    default: "Url"
runs:
  using: 'node16'
  main: 'index.js'