name: 'notion-action'
description: 'Sync your commits to Notion'
branding:
  icon: 'check-circle'  
  color: 'white'
inputs:
  notion_secret:
    description: 'Notion Secret retrieved from My Integrations on notion.so/my-integrations'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'