on: [push]

jobs:
  Notion_Hook_job:
    runs-on: ubuntu-latest
    name: Sync your commits to Notion
    steps:
      - uses: actions/checkout@v3
      - name: Install node modules
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
      - name: Install dependencies
        run: npm ci
      # - name: Connect to Notion step
      #   id: notion
      #   uses: medievil-inc/NotionHook
      #   with:
      #     notion_secret: ${{ secrets.NOTION_SECRET }}
