on: [push]

jobs:
  Notion_Hook_job:
    runs-on: ubuntu-latest
    name: Sync your commits to Notion
    steps:
      - name: Connect to Notion step
        id: notion
        uses: medievil-inc/NotionHook@1.1
        with:
          notion_secret: ${{ secrets.NOTION_SECRET }}
